version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: music-postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: music_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: music-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres-db

volumes:
  postgres_data: