# URL de conexão: Porta padrão do Postgres é 5432 e o banco que criamos no docker-compose é music_db
spring.datasource.url=jdbc:postgresql://localhost:5432/music_db
spring.datasource.driverClassName=org.postgresql.Driver

# Credenciais idênticas às que definimos no arquivo do Docker
spring.datasource.username=root
spring.datasource.password=admin123

# Configurações do Hibernate / JPA para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Exibe e formata o SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false